import turtle

def draw_a(shift):
    a=turtle.Turtle()
    a.up()
    a.backward(350)
    a.forward(shift)
    a.down()
    a.left(70)
    a.forward(50)
    a.right(140)
    a.forward(50)
    a.left(180)
    a.forward(20)
    a.left(70)
    a.forward(20)
    a.up()
    a.left(60)
    a.forward(20)
    a.left(120)
    a.forward(45)
    a.right(90)
    a.forward(550)
    a.down()

def draw_b(shift):
    b=turtle.Turtle()
    b.up()
    b.backward(330)
    b.forward(shift)
    b.down()
    b.circle(12, 180)
    b.left(180)
    b.circle(12, 180)
    b.left(90)
    b.forward(45)
    b.left(90)
    b.up()
    b.forward(20)
    b.right(90)
    b.forward(550)
    b.down()

def draw_c(shift):
    c=turtle.Turtle()
    c.up()
    c.backward(320)
    c.forward(shift)
    c.down()
    c.circle(22,-189)
    c.up()
    c.left(100)
    c.forward(500)
    c.down()

def draw_d(shift):
    d=turtle.Turtle()
    d.up()
    d.backward(350)
    d.forward(shift)
    d.down()
    d.circle(22,180)
    d.left(90)
    d.forward(45)
    d.up()
    d.forward(550)
    d.down()

def draw_e(shift):
    e=turtle.Turtle()
    e.up()
    e.backward(345)
    e.forward(shift)
    e.down()
    e.left(90)
    e.forward(45)
    e.right(90)
    e.forward(20)
    e.left(180)
    e.forward(20)
    e.left(90)
    e.forward(20)
    e.left(90)
    e.forward(20)
    e.backward(20)
    e.right(90)
    e.forward(25)
    e.left(90)
    e.forward(20)
    e.up()
    e.right(90)
    e.forward(550)
    e.down()

def draw_f(shift):
    f=turtle.Turtle()
    f.up()
    f.backward(350)
    f.forward(shift)
    f.down()
    f.left(90)
    f.forward(45)
    f.right(90)
    f.forward(20)
    f.left(180)
    f.forward(20)
    f.left(90)
    f.forward(20)
    f.left(90)
    f.forward(20)
    f.backward(20)
    f.right(90)
    f.forward(25)
    f.up()
    f.forward(550)
    f.down()

def draw_g(shift):
    g = turtle.Turtle()
    g.up()
    g.backward(315)
    g.forward(shift)
    g.down()
    g.circle(22, -189)
    g.left(100)
    g.up()
    g.forward(44)
    g.left(180)
    g.down()
    g.forward(11)
    g.left(90)
    g.forward(11)
    g.up()
    g.left(90)
    g.forward(550)
    g.down()

def draw_h(shift):
    h=turtle.Turtle()
    h.up()
    h.backward(350)
    h.forward(shift)
    h.down()
    h.left(90)
    h.forward(45)
    h.left(180)
    h.forward(23)
    h.left(90)
    h.forward(20)
    h.left(90)
    h.up()
    h.forward(23)
    h.left(180)
    h.down()
    h.forward(45)
    h.up()
    h.forward(500)
    h.down()

def draw_i(shift):
    i = turtle.Turtle()
    i.up()
    i.backward(330)
    i.forward(shift)
    i.down()
    i.left(90)
    i.forward(45)
    i.up()
    i.left(180)
    i.forward(550)
    i.down()

def draw_j(shift):
    j = turtle.Turtle()
    j.up()
    j.backward(330)
    j.forward(shift)
    j.down()
    j.left(90)
    j.forward(45)
    j.left(180)
    j.forward(45)
    j.right(90)
    j.circle(-5, 180)
    j.up()
    j.right(150)
    j.forward(550)
    j.down()

def draw_k(shift):
    k = turtle.Turtle()
    k.up()
    k.backward(350)
    k.forward(shift)
    k.down()
    k.left(90)
    k.forward(45)
    k.left(180)
    k.forward(23)
    k.left(45)
    k.forward(32)
    k.left(180)
    k.forward(32)
    k.right(90)
    k.forward(32)
    k.right(135)
    k.up()
    k.forward(500)
    k.down()

def draw_l(shift):
    l = turtle.Turtle()
    l.up()
    l.backward(350)
    l.forward(shift)
    l.down()
    l.left(90)
    l.forward(45)
    l.left(180)
    l.forward(45)
    l.left(90)
    l.forward(30)
    l.right(90)
    l.up()
    l.forward(500)
    l.down()

def draw_m(shift):
    m = turtle.Turtle()
    m.up()
    m.backward(350)
    m.forward(shift)
    m.down()
    m.left(90)
    m.forward(45)
    m.right(135)
    m.forward(30)
    m.left(90)
    m.forward(30)
    m.right(135)
    m.forward(45)
    m.up()
    m.forward(500)
    m.down()


def draw_n(shift):
    n = turtle.Turtle()
    n.up()
    n.backward(340)
    n.forward(shift)
    n.down()
    n.left(90)
    n.forward(45)
    n.right(150)
    n.forward(52)
    n.left(150)
    n.forward(45)
    n.left(180)
    n.forward(45)
    n.up()
    n.forward(500)
    n.down()

def draw_o(shift):
    o = turtle.Turtle()
    o.up()
    o.backward(320)
    o.forward(shift)
    o.down()
    o.circle(23,360)
    o.right(90)
    o.up()
    o.forward(500)
    o.down()

def draw_p(shift):
    p = turtle.Turtle()
    p.up()
    p.backward(350)
    p.forward(shift)
    p.down()
    p.left(90)
    p.forward(45)
    p.left(90)
    p.circle(12,-180)
    p.right(90)
    p.up()
    p.forward(500)
    p.down()

def draw_q(shift):
    q = turtle.Turtle()
    q.up()
    q.backward(350)
    q.forward(shift)
    q.down()
    q.circle(23, 360)
    q.right(30)
    q.forward(10)
    q.right(60)
    q.up()
    q.forward(500)
    q.down()

def draw_r(shift):
    r = turtle.Turtle()
    r.up()
    r.backward(340)
    r.forward(shift)
    r.down()
    r.left(90)
    r.forward(45)
    r.left(90)
    r.circle(12,-180)
    r.right(60)
    r.forward(25)
    r.right(30)
    r.up()
    r.forward(500)
    r.down()

def draw_s(shift):
    s = turtle.Turtle()
    s.up()
    s.backward(350)
    s.forward(shift)
    s.down()
    s.forward(8)
    s.circle(12,180)
    s.circle(-12,180)
    s.forward(8)
    s.right(90)
    s.up()
    s.forward(500)
    s.down()

def draw_t(shift):
    t = turtle.Turtle()
    t.up()
    t.backward(345)
    t.forward(shift)
    t.down()
    t.left(90)
    t.forward(45)
    t.left(90)
    t.forward(15)
    t.left(180)
    t.forward(30)
    t.up()
    t.right(90)
    t.forward(500)
    t.down()

def draw_u(shift):
    u = turtle.Turtle()
    u.up()
    u.backward(345)
    u.forward(shift)
    u.left(90)
    u.forward(45)
    u.left(180)
    u.down()
    u.forward(35)
    u.circle(12,180)
    u.forward(35)
    u.left(180)
    u.up()
    u.forward(500)
    u.down()

def draw_v(shift):
    v = turtle.Turtle()
    v.up()
    v.backward(340)
    v.forward(shift)
    v.down()
    v.left(90)
    v.left(20)
    v.forward(50)
    v.left(180)
    v.forward(50)
    v.left(140)
    v.forward(50)
    v.right(160)
    v.up()
    v.forward(500)
    v.down()

def draw_w(shift):
    w = turtle.Turtle()
    w.up()
    w.backward(340)
    w.forward(shift)
    w.down()
    w.left(90)
    w.left(20)
    w.forward(50)
    w.left(180)
    w.forward(50)
    w.left(120)
    w.forward(25)
    w.right(100)
    w.forward(25)
    w.left(120)
    w.forward(50)
    w.up()
    w.right(160)
    w.forward(500)
    w.down()

def draw_x(shift):
    x = turtle.Turtle()
    x.up()
    x.backward(350)
    x.forward(shift)
    x.down()
    x.left(90)
    x.right(40)
    x.forward(50)
    x.left(180)
    x.forward(50)
    x.left(130)
    x.up()
    x.forward(30)
    x.down()
    x.left(120)
    x.forward(50)
    x.left(150)
    x.up()
    x.forward(500)
    x.down()

def draw_y(shift):
    y = turtle.Turtle()
    y.up()
    y.backward(350)
    y.forward(shift)
    y.down()
    y.left(90)
    y.right(35)
    y.forward(50)
    y.left(180)
    y.forward(20)
    y.right(100)
    y.forward(25)
    y.left(135)
    y.up()
    y.forward(500)
    y.down()

def draw_z(shift):
    z = turtle.Turtle()
    z.up()
    z.backward(300)
    z.forward(shift)
    z.down()
    z.backward(50)
    z.left(45)
    z.forward(55)
    z.left(135)
    z.forward(50)
    z.left(90)
    z.up()
    z.forward(500)
    z.down()

def draw_dot(shift):
    dot = turtle.Turtle()
    dot.up()
    dot.backward(350)
    dot.forward(shift)
    dot.down()
    dot.circle(2,360)
    dot.left(90)
    dot.up()
    dot.forward(500)
    dot.down()

def draw_exclam(shift):
    exclam = turtle.Turtle()
    exclam.up()
    exclam.backward(350)
    exclam.forward(shift)
    exclam.down()
    exclam.circle(2, 360)
    exclam.left(90)
    exclam.up()
    exclam.forward(10)
    exclam.down()
    exclam.forward(30)
    exclam.left(180)
    exclam.up()
    exclam.forward(500)
    exclam.down()

def draw_question(shift):
    que = turtle.Turtle()
    que.up()
    que.backward(350)
    que.forward(shift)
    que.down()
    que.circle(2, 360)
    que.left(90)
    que.up()
    que.forward(10)
    que.down()
    que.forward(15)
    que.right(90)
    que.circle(12, 180)
    que.left(90)
    que.up()
    que.forward(500)
    que.down()